
---
spring:
  config.activate.on-profile: mocked
  sql.init.schema-locations: classpath:schema-h2.sql
  
cds:
  application.services:
      - name: API_BUSINESS_PARTNER-mocked
        model: API_BUSINESS_PARTNER
        serve.path: API_BUSINESS_PARTNER
  remote.services:
    API_BUSINESS_PARTNER:
      destination:
         name: "s4-business-partner-api-mocked"
         type: "odata-v2"
