
spring:
  config.activate.on-profile: cloud
  sql.init.schema-locations: 'classpath:schema-h2.sql'
cds:
  remote.services:
    - name: API_BUSINESS_PARTNER
      destination:
        name: s4-business-partner-api
        suffix: /sap/opu/odata/sap
        type: odata-v2
