---
spring:
  config.activate.on-profile: default
  sql.init.schema-locations: classpath:schema-h2.sql
cds:
  datasource:
    auto-config.enabled: false
  security:
    mock:
      users:
        - name: mock
          password: mock@123
          additional:
            firstName: Klaus
            lastName: Sussard
            email: mock@mail.com
