
---
spring:
  web.resources.static-locations: "file:./app"
  config.activate.on-profile: default
  sql.init.schema-locations: classpath:schema-h2.sql
cds:
  datasource.auto-config.enabled: false
  odata-v4.endpoint.path: "/api"
  
