
---
spring:
  config.activate.on-profile: default
  sql.init.schema-locations: classpath:schema-h2.sql
  security:
    user:
      name: admin
      password: nimda
cds:
  datasource.auto-config.enabled: false
