
---
spring:
  config.activate.on-profile: default
  sql.init.schema-locations: classpath:schema-h2.sql
cds:
  datasource:auto-config.enabled: false
  security:
    mock:
      users:
        - name: anne
          password: pass_anne
          additional:
            firstName: Anne
            lastName: Rose
            email: anne.rose@mail.com
        - name: mia
          password: pass_mia
          additional:
            firstName: Mia
            lastName: Bonnellac
            email: Mia.Bonnellac@mail.com
        - name: sabine
          password: pass_sabine
          roles:
            - Administrators
          additional:
            firstName: Sabine
            lastName: Autumnpike
            email: Sabine.Autumnpike@mail.com
